# Generated by Django 5.0.6 on 2025-01-25 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 18, 16, 24, 833854, tzinfo=datetime.timezone.utc)),
        ),
    ]
